Add package release date to changelog
pxblue/angular-workflows pull request #68
Opened 2021-04-12 16:44 UTC by daileytj

Fixes PXBLUE-1958

#### Changes proposed in this Pull Request:
- Add package release dates to changelog

2021-04-12 19:47 UTC, jeffvg approved these changes

2021-04-12 21:56 UTC, joebochill requested changes

2021-04-12 21:56 UTC, joebochill commented on login-workflow/CHANGELOG.md
> +## v1.0.1 (December 31, 2020)
1.0.1 was published before 1.0.0? I think 1.0.0 should read 2020

2021-04-13 15:35 UTC, joebochill approved these changes

2021-04-13 15:35 UTC, merged